import { useEffect, useMemo, useState } from 'react';
import {
  Activity, AlertTriangle, Box, CheckCircle2, ChevronRight, CircleDot, Cpu, Database,
  ExternalLink, FileText, Gauge, HardDrive, Layers3, LayoutDashboard, Menu, Moon, Network,
  Package, PanelLeftClose, PanelLeftOpen, RefreshCw, Search, Server, Settings2, Sun, Terminal,
  X, Zap
} from 'lucide-react';
import { api } from './api';

const nav = [
  { key: 'overview', label: 'Overview', icon: LayoutDashboard },
  { key: 'nodes', label: 'Nodes', icon: Server },
  { key: 'namespaces', label: 'Namespaces', icon: Layers3 },
  { key: 'pods', label: 'Pods', icon: Box },
  { key: 'deployments', label: 'Deployments', icon: Package },
  { key: 'services', label: 'Services', icon: Network },
  { key: 'ingresses', label: 'Ingress', icon: ExternalLink },
  { key: 'events', label: 'Events', icon: Activity },
];

const formatDate = (value) => value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : '—';
const age = (value) => value ? `${Math.max(0, Math.floor((Date.now() - new Date(value)) / 86400000))}d` : '—';
const display = (value) => value === null || value === undefined || value === '' ? '—' : String(value);
const statusTone = (value = '') => String(value).toLowerCase().replace('notready', 'danger').replace('failed', 'danger').replace('warning', 'warning').replace('critical', 'danger').replace('ready', 'success').replace('running', 'success').replace('available', 'success').replace('healthy', 'success').replace('pending', 'warning').replace('progressing', 'info');

function useResource(loader, dependencies = []) {
  const [state, setState] = useState({ loading: true, data: null, error: null });
  const reload = () => {
    setState({ loading: true, data: null, error: null });
    loader().then((data) => setState({ loading: false, data, error: null })).catch((error) => setState({ loading: false, data: null, error }));
  };
  useEffect(reload, dependencies);
  return { ...state, reload };
}

function Badge({ children, tone }) { return <span className={`badge ${tone || statusTone(children)}`}><span className="badge-dot" />{display(children)}</span>; }
function Empty({ title = 'No resources found', text = 'The backend returned an empty collection.' }) { return <div className="empty"><CircleDot size={22} /><strong>{title}</strong><span>{text}</span></div>; }
function ErrorState({ error, reload }) { return <div className="error-state"><AlertTriangle size={22} /><div><strong>Backend request failed</strong><span>{error?.message || 'Unable to load this resource.'}</span></div><button className="button subtle" onClick={reload}><RefreshCw size={15} /> Retry</button></div>; }
function Loading({ rows = 5 }) { return <div className="skeleton-list">{Array.from({ length: rows }, (_, i) => <div className="skeleton-row" key={i}><span /><span /><span /><span /></div>)}</div>; }
function Metric({ icon: Icon, label, value, detail, accent = 'teal' }) { return <div className={`metric metric-${accent}`}><div className="metric-icon"><Icon size={18} /></div><div><span>{label}</span><strong>{display(value)}</strong><small>{detail}</small></div></div>; }
function Toolbar({ search, setSearch, onRefresh, children }) { return <div className="toolbar"><div className="search"><Search size={16} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Filter resources..." /></div>{children}<button className="icon-button" title="Refresh" onClick={onRefresh}><RefreshCw size={16} /></button></div>; }
function Table({ columns, rows, onRow, emptyTitle }) { if (!rows.length) return <Empty title={emptyTitle} />; return <div className="table-wrap"><table><thead><tr>{columns.map((column) => <th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row.id || row.name || index} onClick={() => onRow?.(row)} className={onRow ? 'clickable' : ''}>{columns.map((column) => <td key={column.key}>{column.render ? column.render(row) : display(row[column.key])}</td>)}</tr>)}</tbody></table></div>; }
function PageHeader({ eyebrow, title, description, action }) { return <div className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>; }

function Overview({ cluster, health, events, loading, reload }) {
  const c = cluster?.data; const recentEvents = (events?.data?.data || []).slice(0, 6); const issues = health?.data?.issues || [];
  return <><PageHeader eyebrow="Cluster / telemetry" title="Operations overview" description="A live view of the resources returned by your Kubernetes control plane." action={<button className="button primary" onClick={reload}><RefreshCw size={16} /> Refresh data</button>} />
    {loading ? <Loading rows={4} /> : <><div className="metrics-grid"><Metric icon={Gauge} label="Cluster health" value={c?.health?.status || health?.data?.status || 'Unknown'} detail={c?.health?.message || `${health?.data?.score ?? '—'} / 100 score`} accent="teal" /><Metric icon={Server} label="Nodes" value={c?.nodes?.total} detail={`${c?.nodes?.ready || 0} ready · ${c?.nodes?.notReady || 0} not ready`} accent="blue" /><Metric icon={Box} label="Pods" value={c?.pods} detail="All namespaces" accent="amber" /><Metric icon={Layers3} label="Namespaces" value={c?.namespaces} detail={`${c?.deployments ?? 0} deployments`} accent="coral" /></div>
      <div className="split-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Control plane</span><h2>Cluster identity</h2></div><Badge tone="success">Connected</Badge></div><div className="identity-grid"><div><span>Context</span><strong>{display(c?.context)}</strong></div><div><span>Cluster</span><strong>{display(c?.cluster)}</strong></div><div><span>Server</span><strong>{display(c?.server)}</strong></div><div><span>Kubernetes</span><strong>{display(c?.version?.gitVersion || c?.version?.gitVersion)}</strong></div></div><div className="unsupported"><Gauge size={17} /><span>Live CPU and memory usage are not exposed by the backend. Capacity and allocatable values are available on the Nodes page.</span></div></section>
        <section className="panel"><div className="panel-head"><div><span className="eyebrow">Signal</span><h2>Health findings</h2></div><button className="text-button" onClick={() => window.location.hash = '#events'}>View events <ChevronRight size={15} /></button></div>{issues.length ? <div className="issue-list">{issues.slice(0, 5).map((issue, i) => <div className="issue" key={i}><Badge tone={issue.severity === 'critical' ? 'danger' : 'warning'}>{issue.severity}</Badge><div><strong>{issue.resourceName}</strong><span>{issue.message}</span></div></div>)}</div> : <Empty title="No active findings" text="Diagnostics returned a clean cluster signal." />}</section></div>
      <section className="panel"><div className="panel-head"><div><span className="eyebrow">Recent activity</span><h2>Cluster events</h2></div><span className="muted">Newest first</span></div><EventTable events={recentEvents} /></section></>}
  </>;
}

function EventTable({ events }) { return <Table rows={events} emptyTitle="No recent events" columns={[{ key: 'type', label: 'Type', render: (r) => <Badge tone={r.type === 'Warning' ? 'warning' : 'info'}>{r.type || 'Normal'}</Badge> }, { key: 'reason', label: 'Reason' }, { key: 'involvedObject', label: 'Object', render: (r) => <span className="mono">{r.involvedObject?.display || '—'}</span> }, { key: 'message', label: 'Message', render: (r) => <span className="truncate">{r.message}</span> }, { key: 'lastTimestamp', label: 'Last seen', render: (r) => formatDate(r.lastTimestamp || r.firstTimestamp) }]}/>; }

function Nodes({ onSelect }) { const resource = useResource(api.nodes); const rows = resource.data?.data || []; return <><PageHeader eyebrow="Infrastructure" title="Nodes" description="Readiness, roles, capacity, and condition signals from every cluster node." action={<button className="button subtle" onClick={resource.reload}><RefreshCw size={16} /> Refresh</button>} />{resource.loading ? <Loading /> : resource.error ? <ErrorState error={resource.error} reload={resource.reload} /> : <Table rows={rows} onRow={onSelect} emptyTitle="No nodes returned" columns={[{ key: 'name', label: 'Node', render: (r) => <strong className="resource-name"><Server size={16} />{r.name}</strong> }, { key: 'status', label: 'Status', render: (r) => <Badge>{r.status}</Badge> }, { key: 'roles', label: 'Roles', render: (r) => r.roles?.join(', ') || '—' }, { key: 'kubernetesVersion', label: 'Version' }, { key: 'cpuCapacity', label: 'CPU capacity', render: (r) => <span className="mono">{display(r.cpuCapacity)}</span> }, { key: 'memoryCapacity', label: 'Memory capacity', render: (r) => <span className="mono">{display(r.memoryCapacity)}</span> }, { key: 'creationTimestamp', label: 'Age', render: (r) => age(r.creationTimestamp) }]}/>}</>; }

function Namespaces({ onSelect }) { const resource = useResource(api.namespaces); const rows = resource.data?.data || []; return <><PageHeader eyebrow="Organization" title="Namespaces" description="Namespace lifecycle and labels returned by the core API." action={<button className="button subtle" onClick={resource.reload}><RefreshCw size={16} /> Refresh</button>} />{resource.loading ? <Loading /> : resource.error ? <ErrorState error={resource.error} reload={resource.reload} /> : <Table rows={rows} onRow={onSelect} emptyTitle="No namespaces returned" columns={[{ key: 'name', label: 'Namespace', render: (r) => <strong className="resource-name"><Layers3 size={16} />{r.name}</strong> }, { key: 'status', label: 'Status', render: (r) => <Badge>{r.status}</Badge> }, { key: 'creationTimestamp', label: 'Created', render: (r) => formatDate(r.creationTimestamp) }, { key: 'labels', label: 'Labels', render: (r) => Object.keys(r.labels || {}).length || '—' }, { key: 'resourceSummary', label: 'Resource summary', render: () => <span className="muted">Not exposed</span> }]}/>}</>; }

function Pods({ onSelect }) { const [namespace, setNamespace] = useState(''); const [search, setSearch] = useState(''); const resource = useResource(() => api.pods(namespace), [namespace]); const rows = (resource.data?.data || []).filter((r) => `${r.name} ${r.namespace}`.toLowerCase().includes(search.toLowerCase())); return <><PageHeader eyebrow="Workloads" title="Pods" description="Inspect pod health, placement, readiness, and container state across namespaces." action={<button className="button subtle" onClick={resource.reload}><RefreshCw size={16} /> Refresh</button>} /><Toolbar search={search} setSearch={setSearch} onRefresh={resource.reload}><input className="select" value={namespace} onChange={(e) => setNamespace(e.target.value)} placeholder="All namespaces" /></Toolbar>{resource.loading ? <Loading /> : resource.error ? <ErrorState error={resource.error} reload={resource.reload} /> : <Table rows={rows} onRow={onSelect} emptyTitle="No matching pods" columns={[{ key: 'name', label: 'Pod', render: (r) => <strong className="resource-name"><Box size={16} />{r.name}</strong> }, { key: 'namespace', label: 'Namespace' }, { key: 'status', label: 'Status', render: (r) => <Badge>{r.status}</Badge> }, { key: 'readiness', label: 'Ready', render: (r) => `${r.readiness?.ready || 0}/${r.readiness?.total || 0}` }, { key: 'restartCount', label: 'Restarts' }, { key: 'nodeName', label: 'Node' }, { key: 'podIP', label: 'IP', render: (r) => <span className="mono">{display(r.podIP)}</span> }, { key: 'creationTimestamp', label: 'Age', render: (r) => age(r.creationTimestamp) }]}/>}</>; }

function Deployments({ onSelect }) { const [namespace, setNamespace] = useState(''); const [search, setSearch] = useState(''); const resource = useResource(() => api.deployments(namespace), [namespace]); const rows = (resource.data?.data || []).filter((r) => `${r.name} ${r.namespace}`.toLowerCase().includes(search.toLowerCase())); return <><PageHeader eyebrow="Workloads" title="Deployments" description="Replica health and rollout state for applications across the cluster." action={<button className="button subtle" onClick={resource.reload}><RefreshCw size={16} /> Refresh</button>} /><Toolbar search={search} setSearch={setSearch} onRefresh={resource.reload}><input className="select" value={namespace} onChange={(e) => setNamespace(e.target.value)} placeholder="All namespaces" /></Toolbar>{resource.loading ? <Loading /> : resource.error ? <ErrorState error={resource.error} reload={resource.reload} /> : <Table rows={rows} onRow={onSelect} emptyTitle="No matching deployments" columns={[{ key: 'name', label: 'Deployment', render: (r) => <strong className="resource-name"><Package size={16} />{r.name}</strong> }, { key: 'namespace', label: 'Namespace' }, { key: 'status', label: 'Status', render: (r) => <Badge>{r.status}</Badge> }, { key: 'desiredReplicas', label: 'Desired' }, { key: 'availableReplicas', label: 'Available' }, { key: 'readyReplicas', label: 'Ready' }, { key: 'updatedReplicas', label: 'Updated' }, { key: 'creationTimestamp', label: 'Age', render: (r) => age(r.creationTimestamp) }]}/>}</>; }

function Services({ type = 'services' }) { const [namespace, setNamespace] = useState(''); const [search, setSearch] = useState(''); const loader = type === 'ingresses' ? api.ingresses : api.services; const resource = useResource(() => loader(namespace), [namespace]); const rows = (resource.data?.data || []).filter((r) => `${r.name} ${r.namespace}`.toLowerCase().includes(search.toLowerCase())); const ingress = type === 'ingresses'; return <><PageHeader eyebrow="Networking" title={ingress ? 'Ingress' : 'Services'} description={ingress ? 'HTTP entry points, hosts, paths, and load balancer addresses.' : 'Service discovery endpoints and exposed ports.'} action={<button className="button subtle" onClick={resource.reload}><RefreshCw size={16} /> Refresh</button>} /><Toolbar search={search} setSearch={setSearch} onRefresh={resource.reload}><input className="select" value={namespace} onChange={(e) => setNamespace(e.target.value)} placeholder="All namespaces" /></Toolbar>{resource.loading ? <Loading /> : resource.error ? <ErrorState error={resource.error} reload={resource.reload} /> : ingress ? <Table rows={rows} emptyTitle="No ingress resources" columns={[{ key: 'name', label: 'Ingress', render: (r) => <strong className="resource-name"><ExternalLink size={16} />{r.name}</strong> }, { key: 'namespace', label: 'Namespace' }, { key: 'hosts', label: 'Hosts', render: (r) => r.hosts?.join(', ') || '—' }, { key: 'addresses', label: 'Addresses', render: (r) => r.addresses?.map((a) => a.ip || a.hostname).join(', ') || '—' }, { key: 'ingressClass', label: 'Class' }, { key: 'creationTimestamp', label: 'Age', render: (r) => age(r.creationTimestamp) }]}/> : <Table rows={rows} emptyTitle="No services returned" columns={[{ key: 'name', label: 'Service', render: (r) => <strong className="resource-name"><Network size={16} />{r.name}</strong> }, { key: 'namespace', label: 'Namespace' }, { key: 'type', label: 'Type', render: (r) => <Badge tone="info">{r.type}</Badge> }, { key: 'clusterIP', label: 'Cluster IP', render: (r) => <span className="mono">{display(r.clusterIP)}</span> }, { key: 'externalIPs', label: 'External IP', render: (r) => r.externalIPs?.join(', ') || '—' }, { key: 'ports', label: 'Ports', render: (r) => r.ports?.map((p) => `${p.port}${p.nodePort ? `:${p.nodePort}` : ''}/${p.protocol}`).join(', ') || '—' }, { key: 'creationTimestamp', label: 'Age', render: (r) => age(r.creationTimestamp) }]}/>}</>; }

function Events() { const [namespace, setNamespace] = useState(''); const [search, setSearch] = useState(''); const resource = useResource(() => api.events(namespace), [namespace]); const rows = (resource.data?.data || []).filter((r) => `${r.reason} ${r.message} ${r.involvedObject?.display}`.toLowerCase().includes(search.toLowerCase())); return <><PageHeader eyebrow="Observability" title="Events" description="Newest-first signals emitted by Kubernetes resources." action={<button className="button subtle" onClick={resource.reload}><RefreshCw size={16} /> Refresh</button>} /><Toolbar search={search} setSearch={setSearch} onRefresh={resource.reload}><input className="select" value={namespace} onChange={(e) => setNamespace(e.target.value)} placeholder="All namespaces" /></Toolbar>{resource.loading ? <Loading /> : resource.error ? <ErrorState error={resource.error} reload={resource.reload} /> : <EventTable events={rows} />}</>; }

function DetailPanel({ title, children, onClose }) { return <div className="backdrop" onClick={onClose}><aside className="detail-panel" onClick={(e) => e.stopPropagation()}><button className="close-button" onClick={onClose}><X size={18} /></button><span className="eyebrow">Resource detail</span><h2>{title}</h2>{children}</aside></div>; }
function KeyValues({ values }) { return <div className="kv-grid">{Object.entries(values).map(([key, value]) => <div key={key}><span>{key}</span><strong>{typeof value === 'object' ? JSON.stringify(value) : display(value)}</strong></div>)}</div>; }
function NodeDetail({ node, onClose }) { return <DetailPanel title={node.name} onClose={onClose}><Badge>{node.status}</Badge><KeyValues values={{ Roles: node.roles?.join(', '), Version: node.kubernetesVersion, OS: node.os, Architecture: node.architecture, 'CPU capacity': node.cpuCapacity, 'Memory capacity': node.memoryCapacity, 'Allocatable CPU': node.allocatableCpu, 'Allocatable memory': node.allocatableMemory }} /><div className="unsupported"><Gauge size={17} /><span>Current CPU and memory usage are not available from the backend.</span></div><h3>Conditions</h3><div className="mini-list">{node.conditions?.map((condition, i) => <div key={i}><Badge tone={condition.status === 'True' ? 'success' : 'warning'}>{condition.type}</Badge><span>{condition.message || condition.reason || condition.status}</span></div>)}</div></DetailPanel>; }
function NamespaceDetail({ namespace, onClose }) { return <DetailPanel title={namespace.name} onClose={onClose}><Badge>{namespace.status}</Badge><KeyValues values={{ Status: namespace.status, Created: formatDate(namespace.creationTimestamp), Labels: Object.keys(namespace.labels || {}).length }} /><div className="unsupported"><Layers3 size={17} /><span>Per-namespace pod, deployment, service, quota, CPU, and memory totals are not exposed by the backend.</span></div></DetailPanel>; }
function PodDetail({ pod, onClose }) { const detail = useResource(() => api.pod(pod.namespace, pod.name), [pod.namespace, pod.name]); const [showLogs, setShowLogs] = useState(false); return <DetailPanel title={pod.name} onClose={onClose}>{detail.loading ? <Loading rows={3} /> : detail.error ? <ErrorState error={detail.error} reload={detail.reload} /> : <><Badge>{detail.data?.status?.phase || pod.status}</Badge><KeyValues values={{ Namespace: detail.data?.metadata?.namespace, Node: detail.data?.node, IP: detail.data?.ip, Restarts: detail.data?.restartCount, ServiceAccount: detail.data?.spec?.serviceAccountName, Created: formatDate(detail.data?.metadata?.creationTimestamp) }} /><div className="detail-actions"><button className="button primary" onClick={() => setShowLogs(true)}><Terminal size={16} /> View logs</button></div><h3>Containers</h3><div className="mini-list">{detail.data?.containers?.map((container) => <div key={container.name}><strong>{container.name}</strong><span>{container.image}</span></div>)}</div><h3>Related events</h3><EventTable events={detail.data?.events || []} /></>}{showLogs && <Logs pod={pod} onClose={() => setShowLogs(false)} />}</DetailPanel>; }
function Logs({ pod, onClose }) { const [container, setContainer] = useState(''); const [previous, setPrevious] = useState(false); const [tailLines, setTailLines] = useState(200); const [auto, setAuto] = useState(false); const resource = useResource(() => api.logs(pod.namespace, pod.name, { container, tailLines, previous }), [pod.namespace, pod.name, container, tailLines, previous, auto ? Date.now() : 0]); return <div className="log-modal"><div className="log-head"><div><span className="eyebrow">Pod logs</span><h3>{pod.name}</h3></div><button className="close-button" onClick={onClose}><X size={18} /></button></div><div className="log-controls"><input className="select" value={container} onChange={(e) => setContainer(e.target.value)} placeholder="Container (optional)" /><input className="number-input" type="number" min="1" max="10000" value={tailLines} onChange={(e) => setTailLines(e.target.value)} /><label className="check"><input type="checkbox" checked={previous} onChange={(e) => setPrevious(e.target.checked)} /> Previous</label><label className="check"><input type="checkbox" checked={auto} onChange={(e) => setAuto(e.target.checked)} /> Auto-refresh</label></div>{resource.loading ? <div className="terminal loading-terminal">Loading logs...</div> : resource.error ? <ErrorState error={resource.error} reload={resource.reload} /> : <pre className="terminal">{resource.data?.logs || 'No log output returned.'}</pre>}</div>; }

function App() {
  const [page, setPage] = useState(window.location.hash.slice(1) || 'overview'); const [dark, setDark] = useState(true); const [collapsed, setCollapsed] = useState(false); const [selected, setSelected] = useState(null);
  useEffect(() => { const onHash = () => setPage(window.location.hash.slice(1) || 'overview'); window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash); }, []);
  const cluster = useResource(api.cluster); const health = useResource(api.health); const events = useResource(api.events); const status = useResource(api.status); const overviewReload = () => { cluster.reload(); health.reload(); events.reload(); status.reload(); };
  const title = nav.find((item) => item.key === page)?.label || (page === 'troubleshooting' ? 'Troubleshooting' : 'Overview');
  const content = page === 'overview' ? <Overview cluster={cluster} health={health} events={events} loading={cluster.loading} reload={overviewReload} /> : page === 'nodes' ? <Nodes onSelect={(node) => setSelected({ type: 'node', value: node })} /> : page === 'namespaces' ? <Namespaces onSelect={(namespace) => setSelected({ type: 'namespace', value: namespace })} /> : page === 'pods' ? <Pods onSelect={(pod) => setSelected({ type: 'pod', value: pod })} /> : page === 'deployments' ? <Deployments onSelect={(deployment) => setSelected({ type: 'deployment', value: deployment })} /> : page === 'services' ? <Services /> : page === 'ingresses' ? <Services type="ingresses" /> : page === 'events' ? <Events /> : <Troubleshooting />;
  return <div className={dark ? 'app dark' : 'app'}><aside className={`sidebar ${collapsed ? 'collapsed' : ''}`}><div className="brand"><div className="brand-mark"><Zap size={19} /></div>{!collapsed && <div><strong>Cluster</strong><span>Console</span></div>}</div><button className="collapse" onClick={() => setCollapsed(!collapsed)}>{collapsed ? <PanelLeftOpen size={17} /> : <PanelLeftClose size={17} />}</button><nav>{nav.map(({ key, label, icon: Icon }) => <a className={page === key ? 'active' : ''} href={`#${key}`} key={key} title={collapsed ? label : undefined}><Icon size={18} />{!collapsed && <span>{label}</span>}</a>)}</nav><div className="sidebar-bottom">{!collapsed && <div className="connection"><span className={`pulse ${status.data?.kubernetes === 'connected' ? 'online' : ''}`} /><div><strong>{status.data?.kubernetes === 'connected' ? 'Backend connected' : 'Checking backend'}</strong><span>{api.url}</span></div></div>}<button className="theme-button" onClick={() => setDark(!dark)}>{dark ? <Sun size={17} /> : <Moon size={17} />}{!collapsed && <span>{dark ? 'Light theme' : 'Dark theme'}</span>}</button></div></aside><main className="main"><header className="topbar"><button className="mobile-menu" onClick={() => setCollapsed(!collapsed)}><Menu size={19} /></button><div><span className="topbar-kicker">KUBERNETES / {title.toUpperCase()}</span><strong>{cluster.data?.context || 'Connecting to cluster...'}</strong></div><div className="top-actions"><Badge tone={status.data?.kubernetes === 'connected' ? 'success' : 'warning'}>{status.data?.kubernetes || 'checking'}</Badge><button className="icon-button" title="Settings"><Settings2 size={17} /></button></div></header><div className="content">{content}</div></main>{selected?.type === 'node' && <NodeDetail node={selected.value} onClose={() => setSelected(null)} />}{selected?.type === 'namespace' && <NamespaceDetail namespace={selected.value} onClose={() => setSelected(null)} />}{selected?.type === 'pod' && <PodDetail pod={selected.value} onClose={() => setSelected(null)} />}{selected?.type === 'deployment' && <DeploymentDetail deployment={selected.value} onClose={() => setSelected(null)} />}</div>;
}

function Troubleshooting() { const resource = useResource(api.troubleshooting); const groups = resource.data || {}; return <><PageHeader eyebrow="Observability" title="Troubleshooting" description="Actionable issues grouped by severity from backend diagnostics." action={<button className="button subtle" onClick={resource.reload}><RefreshCw size={16} /> Refresh</button>} />{resource.loading ? <Loading /> : resource.error ? <ErrorState error={resource.error} reload={resource.reload} /> : <div className="diagnostic-grid">{['critical', 'warning', 'info'].map((severity) => <section className="panel" key={severity}><div className="panel-head"><h2>{severity}</h2><Badge tone={severity === 'critical' ? 'danger' : severity === 'warning' ? 'warning' : 'info'}>{groups[severity]?.length || 0}</Badge></div>{groups[severity]?.length ? <div className="issue-list">{groups[severity].map((issue, i) => <div className="issue" key={i}><div><strong>{issue.resourceName}</strong><span>{issue.message}</span><small>{issue.recommendation}</small></div></div>)}</div> : <Empty title={`No ${severity} issues`} text="No diagnostics were returned in this category." />}</section>)}</div>}</>; }
function DeploymentDetail({ deployment, onClose }) { const detail = useResource(() => api.deployment(deployment.namespace, deployment.name), [deployment.namespace, deployment.name]); return <DetailPanel title={deployment.name} onClose={onClose}>{detail.loading ? <Loading rows={3} /> : detail.error ? <ErrorState error={detail.error} reload={detail.reload} /> : <><Badge>{detail.data?.summary?.status || deployment.status}</Badge><KeyValues values={{ Namespace: detail.data?.metadata?.namespace, Desired: detail.data?.summary?.desiredReplicas, Available: detail.data?.summary?.availableReplicas, Ready: detail.data?.summary?.readyReplicas, Updated: detail.data?.summary?.updatedReplicas, Created: formatDate(detail.data?.metadata?.creationTimestamp) }} /><h3>Strategy</h3><pre className="json-block">{JSON.stringify(detail.data?.spec?.strategy || {}, null, 2)}</pre></>}</DetailPanel>; }

export default App;
